[project]
<<<<<<< HEAD
name = "ecommerce-sales-pipeline"
version = "0.1.0"
description = ""
authors = [
    {name = "ambrecazaux",email = "ambre.charlotte.cazaux@gmail.com"}
=======
name = "mental-health-pipeline"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
>>>>>>> 7d23c111ca42ccf03b072b2527d2a4be4296f6a7
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
<<<<<<< HEAD
]

[tool.poetry]
packages = [{include = "ecommerce_sales_pipeline", from = "src"}]
=======
    "pandas (>=2.3.1,<3.0.0)"
]

[tool.poetry]
packages = [{include = "mental_health_pipeline", from = "src"}]
>>>>>>> 7d23c111ca42ccf03b072b2527d2a4be4296f6a7


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
